name: Tests
on: [push]

jobs:
  ruby:
    name: Ruby Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Ruby Setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run the tests
        run: bundle exec rake test
